import { StyleSheet, Dimensions } from "react-native";
const { height } = Dimensions.get('window');

export default StyleSheet.create({
  scrollContainer: {
    flexGrow: 1,
    minHeight: height,
    justifyContent: "center",
    backgroundColor: "#FCFCF7",
  },
  centralizador: {
    width: "100%",
    alignItems: "stretch",
    justifyContent: "center",
    flex: 1,
  },
  title: {
    fontFamily: "OpenSans-Bold",
    fontSize: 28,
    color: "#2584E8",
    marginBottom: 28,
    alignSelf: "center",
    letterSpacing: 0.2,
  },
  form: {
    width: "88%",
    alignSelf: "center",
    marginBottom: 10,
  },
  input: {
    width: "100%",
    backgroundColor: "#F4F6FA",
    borderRadius: 12,
    paddingHorizontal: 18,
    paddingVertical: 14,
    fontFamily: "OpenSans-Regular",
    fontSize: 16,
    color: "#222",
    marginBottom: 13,
    borderWidth: 1,
    borderColor: "#E1E8F0",
  },
  senhaWrapper: {
    width: "100%",
    position: "relative",
    marginBottom: 13,
  },
  olho: {
    position: "absolute",
    right: 15,
    top: "30%",
    height: 30,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
  },
  button: {
    width: "88%",
    alignSelf: "center",
    backgroundColor: "#3B9AF2",
    borderRadius: 24,
    paddingVertical: 15,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
    marginBottom: 12,
    shadowColor: "#222",
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 3,
  },
  buttonText: {
    fontFamily: "OpenSans-SemiBold",
    fontSize: 18,
    color: "#fff",
    textTransform: "capitalize",
    letterSpacing: 0.2,
  },
  linkContainer: {
    width: "100%",
    alignItems: "center",
    marginTop: 6,
  },
  linkText: {
    fontFamily: "OpenSans-SemiBold",
    fontSize: 15,
    color: "#2584E8",
    textAlign: "center",
    marginTop: 0,
  },
});
