import { StyleSheet, Platform } from "react-native";

export default StyleSheet.create({
  tela: {
    flex: 1,
    backgroundColor: "#FCFCF7",
  },
  conteudo: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 0,
    paddingBottom: 60,
  },
  titulo: {
    fontFamily: "OpenSans-Bold",
    fontSize: 23,
    color: "#2584E8",
    marginTop: 36,
    marginBottom: 18,
    textAlign: "center",
},
card: {
    width: "90%",
    backgroundColor: "#fff",
    borderRadius: 22,
    padding: 20,
    marginTop: 10,
    marginBottom: 30,
    alignSelf: "center",
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 7,
    elevation: 2,
},
label: {
    fontFamily: "OpenSans-SemiBold",
    color: "#2584E8",
    fontSize: 15,
    marginTop: 9,
    marginBottom: 5,
},
tiposRow: {
    flexDirection: "row",
    marginBottom: 12,
    flexWrap: "wrap",
    justifyContent: "space-between",
},
tipoBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#E9F2FE",
    paddingVertical: 7,
    paddingHorizontal: 12,
    borderRadius: 16,
    marginRight: 7,
    marginBottom: 7,
},
tipoBtnAtivo: {
    backgroundColor: "#2584E8",
},
tipoTxt: {
    fontFamily: "OpenSans-SemiBold",
    color: "#2584E8",
    fontSize: 15,
    marginLeft: 5,
},
input: {
    width: "100%",
    backgroundColor: "#F4F6FA",
    borderRadius: 9,
    paddingHorizontal: 13,
    paddingVertical: Platform.OS === "ios" ? 14 : 9,
    fontFamily: "OpenSans-Regular",
    fontSize: 15.5,
    color: "#222",
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#E1E8F0",
},
fotoBtn: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 7,
    paddingHorizontal: 11,
    backgroundColor: "#E8F1FD",
    borderRadius: 10,
    alignSelf: "flex-start",
    marginTop: 2,
    marginBottom: 7,
},
fotoBtnTxt: {
    color: "#2584E8",
    fontFamily: "OpenSans-SemiBold",
    fontSize: 15,
    marginLeft: 7,
},
fotoPreview: {
    width: 80,
    height: 80,
    borderRadius: 12,
    marginTop: 4,
    marginBottom: 12,
    alignSelf: "center",
},
button: {
    width: "100%",
    backgroundColor: "#3B9AF2",
    borderRadius: 22,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 14,
    shadowColor: "#1976D2",
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 3,
    elevation: 2,
},
buttonText: {
    fontFamily: "OpenSans-SemiBold",
    fontSize: 17,
    color: "#fff",
},
areaBrancaAbaixoNavbar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 34,
    backgroundColor: "#fff",
    zIndex: 1,
},
});
