import { StyleSheet, Dimensions } from "react-native";

const { height } = Dimensions.get("window");

export default StyleSheet.create({
tela: {
    flex: 1,
    backgroundColor: "#fff",
    justifyContent: "center",
},
central: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 100,
},
cardClima: {
    width: "100%",
    maxWidth: 380,
    backgroundColor: "#fff",
    borderRadius: 28,
    alignItems: "center",
    paddingVertical: 20,
    paddingHorizontal: 14,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.09,
    shadowRadius: 10,
    elevation: 4,
},
rowTop: {
    flexDirection: "row",
    width: "100%",
    justifyContent: "space-between",
    marginBottom: 6,
    alignItems: "center",
},
emojiClima: {
    fontSize: 38,
    marginLeft: 6,
},
localizacao: {
    fontSize: 18,
    fontFamily: "OpenSans-SemiBold",
    color: "#2584E8",
    marginBottom: 3,
},
cepRow: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    marginTop: 4,
    marginBottom: 3,
},
cepInput: {
    backgroundColor: "#F4F6FA",
    borderRadius: 8,
    fontSize: 16,
    paddingVertical: 8,
    paddingHorizontal: 14,
    flex: 1,
    borderWidth: 1,
    borderColor: "#E1E8F0",
    marginRight: 8,
    fontFamily: "OpenSans-Regular",
},
cepSalvar: {
    padding: 4,
    borderRadius: 100,
    backgroundColor: "#F1F7FE",
},
cepLabel: {
    fontSize: 15,
    color: "#3B9AF2",
    fontFamily: "OpenSans-Regular",
    marginBottom: 6,
    marginTop: 2,
},
temp: {
    fontSize: 46,
    color: "#222",
    fontFamily: "OpenSans-Bold",
    marginTop: 12,
    marginBottom: 2,
},
cond: {
    fontSize: 17,
    fontFamily: "OpenSans-SemiBold",
    color: "#2584E8",
    marginBottom: 2,
    textAlign: "center",
},
erroMsg: {
    color: "#DA2929",
    fontFamily: "OpenSans-SemiBold",
    marginTop: 24,
    fontSize: 16,
},
separador: {
    height: 8,
},
cardDicas: {
    width: "100%",
    maxWidth: 380,
    backgroundColor: "#E1F2FE",
    borderRadius: 22,
    padding: 16,
    marginBottom: 8,
    alignItems: "flex-start",
},
dicasTitulo: {
    fontSize: 16,
    color: "#2584E8",
    fontFamily: "OpenSans-Bold",
    marginBottom: 7,
},
dicaItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 5,
    marginLeft: 2,
},
dicaTxt: {
    fontSize: 15,
    color: "#3B9AF2",
    fontFamily: "OpenSans-Regular",
},
cardAlertas: {
    width: "100%",
    maxWidth: 380,
    backgroundColor: "#FEF5E6",
    borderRadius: 22,
    padding: 16,
    alignItems: "flex-start",
    marginBottom: 8,
},
alertaTitulo: {
    fontSize: 16,
    color: "#FF9000",
    fontFamily: "OpenSans-Bold",
    marginBottom: 7,
},
alertaItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 5,
    marginLeft: 2,
},
alertaTxt: {
    fontSize: 15,
    color: "#DA8F00",
    fontFamily: "OpenSans-Regular",
},
areaBrancaAbaixoNavbar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 34,
    backgroundColor: "#fff",
    zIndex: 1,
},
});
