import { StyleSheet } from "react-native";

export default StyleSheet.create({
  keyboard: {
    flex: 1,
    backgroundColor: "#FCFCF7",
  },
  container: {
    flex: 1,
    backgroundColor: "#FCFCF7",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
    paddingBottom: 40,
  },
  title: {
    fontFamily: "OpenSans-Bold",
    fontSize: 28,
    color: "#2584E8",
    marginBottom: 36,
    textAlign: "center",
    letterSpacing: 0.2,
  },
  input: {
    width: "100%",
    backgroundColor: "#F4F6FA",
    borderRadius: 12,
    paddingHorizontal: 18,
    paddingVertical: 15,
    fontFamily: "OpenSans-Regular",
    fontSize: 17,
    color: "#222",
    marginBottom: 18,
    borderWidth: 1,
    borderColor: "#E1E8F0",
    shadowColor: "#ccc",
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 1 },
    shadowRadius: 2,
  },
  senhaWrapper: {
    width: "100%",
    position: "relative",
    marginBottom: 18,
  },
  olho: {
    position: "absolute",
    right: 15,
    top: "30%",
    height: 30,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10,
  },
  button: {
    width: "100%",
    backgroundColor: "#3B9AF2",
    borderRadius: 26,
    paddingVertical: 16,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
    marginBottom: 24,
    shadowColor: "#1976D2",
    shadowOpacity: 0.14,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 3,
  },
  buttonText: {
    fontFamily: "OpenSans-SemiBold",
    fontSize: 19,
    color: "#fff",
    textTransform: "capitalize",
    letterSpacing: 0.3,
  },
  linkText: {
    fontFamily: "OpenSans-Regular",
    fontSize: 15,
    color: "#2584E8",
    textAlign: "center",
  },
  linkTextBold: {
    fontFamily: "OpenSans-Bold",
    fontSize: 15,
    color: "#2584E8",
  },
});
